= "Reactive inter-process communication" with Spring WebFlux and Spring Boot 2.0
Reactive Meetup Lucerne https://www.meetup.com/de-DE/Luzern-reactive-concurrent-distributed-solutions-on-the-JVM/
:imagesdir: ./docs

== Introduction

We are a group of software developers with a more or less monthly meetup in https://goo.gl/maps/NpfJhDWsCnw[Lucerne (Switzerland)].
We are interested in programming questions around concurrency, distributed systems, consistency...

We did some learning using different kinds of async non-blocking programming models and libraries
to communicate between objects / functions *inside the same JVM process* in 2017,
see https://github.com/ReactiveMeetupLucerne/AsyncNonBlockingExamplesJVM for the results.

Important for us were especially the libraries implementing the reactive streams interfaces
http://www.reactive-streams.org: https://github.com/ReactiveX/RxJava[RxJava], https://projectreactor.io/[Reactor] and https://akka.io/docs/[Akka-Streams].

With the availability of Spring WebFlux in Spring 5 (Fall 2017) and Spring Boot 2.0 (Spring 2018),
there is now one of the first "big main-stream" implementations available to do "reactive *inter-process* communication".

Spring WebFlux embraces fully Reactor and RxJava, but not Akka-Streams.

To figure out how Spring WebFlux works, we defined some questions regarding features, behaviour and performance.
We try to answer these questions by providing working code examples.

Have fun viewing the results and feel free to provide feedback, improvements or contributions via GitHub issues and pull requests.

Sincerly, +
the participating members of the https://www.meetup.com/de-DE/Luzern-reactive-concurrent-distributed-solutions-on-the-JVM/[Lucerne reactive meetup group]

== Goals for us

* Get some more exercise using Reactor and RxJava
* Get first impressions about how to use Spring WebFlux and Spring Boot 2.0
* Try to get a deeper understanding by asking and answering questions
* Have fun

== Getting started

=== Reactive communication inside the same process

The "reactive" libraries for the JVM like Reactor or RxJava offer a lot of power to implement
parallelism, flow-control, backpressure handling, etc. Think of Java 8 CompletableFuture mixed
with Java 8 Streams, but on steroids.

See e.g. https://github.com/ReactiveMeetupLucerne/AsyncNonBlockingExamplesJVM,
https://www.infoq.com/articles/rxjava-by-example
or link:./src/main/java/a_intro/RxJavaCodeExamples.java[RxJavaCodeExamples.java] for some examples.

=== Hello world "reactive inter-process communication" between two JVM processes

* Reactive hello world server
** link:./src/main/java/b_webflux_helloworld/server/ServerApplication.java[ServerApplication.java]

* Reactive hello world client
** link:./src/main/java/b_webflux_helloworld/client/ClientApplication.java[ClientApplication.java]

* Links for the browser as a client
** http://localhost:8080/restcontroller/reactor/helloworld
** http://localhost:8080/restcontroller/reactor/helloworldslow
** http://localhost:8080/restcontroller/reactor/helloworlddto
** http://localhost:8080/restcontroller/rxjava2/helloworld
** http://localhost:8080/restcontroller/rxjava2/helloworldslow
** http://localhost:8080/restcontroller/rxjava2/helloworlddto
** http://localhost:8080/routerfunction/helloworld
** http://localhost:8080/routerfunction/helloworlddto

=== Learning material

* On Spring WebFlux / Spring Boot
** https://spring.io/blog/2017/03/15/spring-tips-the-spring-web-flux-reactive-client
** https://todd.ginsberg.com/post/springboot2-reactive-kotlin/
** https://spring.io/guides/gs/reactive-rest-service/
** https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#spring-webflux
* On Reactor
** https://projectreactor.io/docs/core/release/reference/
** https://www.infoq.com/articles/reactor-by-example
* On RxJava
** https://www.infoq.com/articles/rxjava-by-example
** http://reactivex.io/
** https://www.pluralsight.com/courses/reactive-programming-java-8-rxjava
** https://www.youtube.com/watch?v=KUoFMCglRlY[Tomasz Nurkiewicz - RxJava in legacy projects]
** http://shop.oreilly.com/product/0636920042228.do[Reactive Programming with RxJava]

== Questions

=== Questions regarding "reactive inter-process communication" between two JVM processes

[cols="1,5,5,2"]
|===
|# |Question |Answer |Code example(s)

|1
|Regarding serialization.

In the hello world example, there is an object of the type `TextDto` transported between the two processes.

What are the requirements for a data type to be transported? e.g. must implement Serializable?
or e.g. must follow the JavaBean convention (setter/getter)?
|Jackson must support it: JavaBean
|link:./src/main/java/question1/Q1Client.java[Q1Client.java] link:./src/main/java/question1/server/Q1Server.java[Q1Server.java]

|2
|Regarding serialization.

In addition to question 1: What mechanism uses Spring WebFlux to marshal/unmarshal the objects? (e.g. JAX-RS, Jackson, GSON, ...)
|TODO
|TODO

|3
|Regarding "compose-ability".

Can you create an example showing how to fetch the price for the flight,
the hotel and the car "in parallel"?

Is this "inter-process" somehow different than in the "inside same process" example
from link:./src/main/java/a_intro/RxJavaCodeExamples.java[RxJavaCodeExamples.java]?
|TODO
|TODO

|4
|Regarding cancellation.

A server-side producer creates a Flux with 1'000'000 values. But the client only
takes 1'000 of them (using the take(1000) operator).

How many values does the server actually produce?

How many values does the client actually receive?
|When running the example for the first time, the server produces around 1013 values and then stops.
The client gets exactly 1000 values. When I run the client example a couple more times,
the server produces around 7000 values and then stops. The client always gets exactly 1000 values.

Works fine!
|link:./src/main/java/question4/client/ClientApplication.java[ClientApplication.java]
link:./src/main/java/question4/server/ServerApplication.java[ServerApplication.java]
|5
|Regarding timeouts/cancellation.

A server-side producer creates a Mono with 1 value, but the value is produced
with a delay of 2 seconds.

The client aborts its call after 1 second using the timeout operator.

Is the cancellation of the client propagated "in time" to the server?
Is the delayed creation of the value on the server-side aborted?
|TODO
|TODO

|6
|Regarding flow-control.

There is a fast producer on the server side and a slow client.
The slow client can only process 1 value every 100ms.
The producer works at "full speed".

Does the producer react on this and eventually start producing fewer values per time?
Do server and client find some common pace?
|The producer reacts on this snail, but only 'cause the tcp-buffer is full. If the buffer frees the lock,
the producer continous producing at full speed until the buffer is full again.
|link:./src/main/java/question6/client/ClientApplication.java[ClientApplication.java]
 link:./src/main/java/question6/server/ServerApplication.java[ServerApplication.java]

|7
|Regarding flow-control.

How is the flow-control from question 6 implemented?

Is there some kind of two-way communication using e.g. HTTP/2?
Or some kind of backpressure on the network level (TCP)?

See https://stackoverflow.com/questions/41772711/backpressure-for-rest-endpoints-with-spring-functional-web-framework#comment70845288_41825959
and https://www.youtube.com/watch?v=oS9w3VenDW0 (watch between 28:20 and 29:20) for some hints.
|TODO
|TODO

|8
|Regarding flow-control.

Assuming there is some kind of buffering used internally as solution in question 6.
Is there a way to configure the "buffer size"?

With "buffer size" I think of number of objects or number of bytes on the network level.
|TODO
|TODO

|9
|Regarding flow-control.

Slow producer (server), fast consumer (client). Is the consumer (client) somehow blocked?
E.g. a thread wasted?
|TODO
|TODO

|10
|Regarding flow-control.

A client zips two Flux from a server together. The two Flux
work on a different speed: One Flux works at full speed, the second Flux
emits only one value every 100ms.

Does the faster server Flux eventually react on that and start producing fewer values per time?
|TODO
|TODO

|11
|Regarding flow-control.

We have 3 processes involved: A fake persistence process (think of a database),
an API gateway process and a client process.

The three processes work at different speeds: The client is very slow
and can only process one value per 100ms. The API gateway process has a bad day
and can only process one value per 50ms. The fake persistence process works at full speed.

Do the faster producers eventually react on the slower consumers?
Do the three process find some common speed?
What's the resulting common speed?
|TODO
|TODO

|12
|Regarding performance.

We have a producer (server) and a consumer (client).
Both working at full speed.

How many kb/sec are transported? How many objects/sec?
|TODO
|TODO

|13
|Regarding latency.

We have a producer (server) with a Mono (single value) and a consumer (client).

What's the approx. latency from subscription-time until the value is received?
|TODO
|TODO

|14
|Regarding errors.

We have a producer (server) with a Flux which delivers first 10 values and
then one error, a RuntimeException("Boom").

How does the error arrive at the client? Type, Stacktrace etc?
|TODO
|TODO

|15
|Regarding errors.

We have a producer (server) with a Flux which delivers first 10 values and
then one error, an exception with a custom data type "MyRuntimeException("Boom")".

How does the error arrive at the client? Type, Stacktrace etc?
|TODO
|TODO

|16
|Regarding errors.

We have a producer (server) which produces an endless stream
of values.

The client processes the frist 10 values and then has an exception
in his own "stream handling" (e.g. a RuntimeException in a map operator).

Is the producer (server) notified by this? Does the producer (server) stop
producing values? How many values does the producer (server) produce?
|TODO
|TODO

|17
|Regarding errors.

Same like question 16. But this time, the client "crashes" (Runtime#halt), instead of the server.

Is the producer (server) notified by this? Does the producer (server) stop
producing values? How many values does the producer (server) produce?
|TODO
|TODO

|18
|Regarding errors.

We have a producer (server) which produces an endless stream
of values. But after 10 values, it crashes (Runtime#halt).

How is the client notified by this?
What kind of error does the client get?
How many values does the client get?
|TODO
|TODO
|===


=== Questions regarding "reactive inter-process communication" between a JVM process and a webbrowser process

TODO

